### ISSUE TITLE
Advanced Chimneys buggy

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#19] opened 2017-10-08 08:11 UTC
Hey, with 1.3.1 the Advanced Chimneys seem to still be pretty Buggy. When amount set to 15 nothing at all Comes out, when set to 50 some come out, but it's not nearly as much as i would expect.

**Comment by D3nnis3n** [comment] 2017-10-09 14:57
Also, when you place a vannila furnace and a chimney next to it, the smoke particles are supposed to go through the chimney - and more of them the more furnaces you put next to the chimney, this is not working with your mod, too.

**Comment by D3nnis3n** [comment] 2017-10-09 14:57
Also i find the smoke particles too less on vanilla furnaces, too.

**Comment by TominoCZ** [comment] 2017-11-22 00:21
This is currently the last issue before the release.. I can't get your mod to work on 1.12.2...

**Comment by TominoCZ** [comment] 2017-11-25 20:34
I will leave this issue open since there is currently no solution for it. The problem is in Avanced Chimneys. Since Advanced Chimney's source code isn't publicly available, I can't do anything to fix it.

**Comment by D3nnis3n** [comment] 2017-11-26 06:13
Maybe you could crosslink this issue to their Tracker? Theyve been helpful
in the past.

Am 25.11.2017 21:34 schrieb "TominoCZ" <notifications@github.com>:

**Comment by EnderLanky** [comment] 2017-12-02 04:36
Hello there, 
The problem is that I use my own emitted particle counter, which increments on smoke particle creation and decrements when the particle expires. So, to fix this issue, you need to properly "destroy" the original particle by calling its setExpired() method.
The best way to do that (IMHO) is to add a reference to the original particle to your fanсy particle class and call setExpired() method from there when it expires.

**Comment by TominoCZ** [comment] 2017-12-02 14:09
@EnderLanky Cool. Now there is one last issue.. the particles should change coolor as they go through the chimneys right? That doesn't happen tho.. also, it looks like the particle's max age is not changing....

**Comment by D3nnis3n** [comment] 2017-12-02 17:48
Thanks for your help, EnderLanky :)

**Comment by TominoCZ** [comment] 2017-12-02 22:52
Fixed in version 2.3.5 :)

**Closed by TominoCZ** 2017-12-02 22:52 UTC
Labels: wontfix
