### ISSUE TITLE
Fancy Block Particles Bug

### ISSUE THREAD

**Issue by ieuangardinerMC** [TominoCZ/FancyBlockParticles#48] opened 2018-02-02 13:53 UTC

**Comment by TominoCZ** [comment] 2018-02-02 14:43
That weird.. I seem to not be able to reproduce this issue..
Everything is working fine for me:
[https://s14.postimg.org/j8dyfdyen/2018-02-02_15.41.29.png](url)¨

Make a screenshot an post it here please.

**Comment by ieuangardinerMC** [comment] 2018-02-05 10:39
Oddly enough the issue isn't happening for me now! But if it happens again I'll be sure to take a screen shot. Sorry for the inconvenience and thanks for the help :)

**Comment by TominoCZ** [comment] 2018-02-11 15:54
I'm not 100% sure, but version 2.3.7 might fix the issue ;)
I'll leave this open in case it happens again.

**Comment by TominoCZ** [comment] 2018-03-04 12:10
I'm closing this issue as it seems that everything works fine since the last update :)

**Closed by TominoCZ** 2018-03-04 12:10 UTC
Labels: on hold
