### ISSUE TITLE
Chisels & Bits have to be placed twice to be really placed

### ISSUE THREAD

**Issue by D3nnis3n** [TominoCZ/FancyBlockParticles#18] opened 2017-10-07 20:19 UTC
When installed your mod in one of the 1.3.x Versions one does Need to place every chisels & bits block two times so it will really be placed in the world, on the first try nothing happens. Could you fix that or tell me how i can disable any chisel & bits blocks for your mod - as those are some hundred thousands id's that seems to be pretty hard to include every single bit, layer, etc. pp.

**Comment by TominoCZ** [comment] 2017-10-08 00:43
Fixed in the upcoming version 2.3.2. Although there is a bug which is not caused by my mod.. Chisels & Bits might be using a custom model which I cannot seem to render atm.. so instead of the placing animation, you'll only see air(until the animation is done). Will look more into it.

**Closed by TominoCZ** 2017-10-08 00:43 UTC

**Comment by D3nnis3n** [comment] 2017-10-08 05:56
As you said there is an issue that is not caused by your mod, should i open an issue on C&B Tracker? I sureley would need more description as to what that bug is. You also, if possible could just ban those C&B bits hardcoded. Or make Wildcards possible or something like that, i just don't know how to ban all those blocks.

But for now it'll be fine if it places on the first try but takes a short time.
