### ISSUE TITLE
Strange Issue with FBP+Optifine (Beta)+BetterFPS

### ISSUE THREAD

**Issue by vpontin** [TominoCZ/FancyBlockParticles#22] opened 2017-10-09 00:54 UTC
Its hard to explain with words, so here's a GIF:

![Animated Screenshot](https://media.giphy.com/media/26n79BRpNc5EiPHPO/giphy.gif)

There is some artifacts when i place saplings (not tested with other 'similar' transparent blocks like flowers and grasses) and solid blocks. 

I'm using:
Minecraft 1.12.2
Forge build 2509
FBP 1.12.2-2.3.1
Optfine preview HD U C7
BetterFPS 1.4.8

**Comment by vpontin** [comment] 2017-10-09 00:55
Darn, seems like Github doesnt accept giphy .gifs.

**Comment by D3nnis3n** [comment] 2017-10-09 03:05
This is happening for most blocks at the moment, was mentioned somewhere on the git.

**Comment by TominoCZ** [comment] 2017-10-15 11:48
The only thing I can think of is the forge version...
The mod was made in forge build 2493.. Try it with that version of forge.
I will switch to the latest versions of forge.

**Comment by D3nnis3n** [comment] 2017-10-15 11:49
At least i can't. I got many mods needing 2503 or higher. I just switched back to 2.2.2, like i did several times before. On that Version everything works fine.

**Comment by TominoCZ** [comment] 2017-10-15 13:52
Thry this: [http://www32.zippyshare.com/v/uzAiM3s9/file.html](url)

It's built with the same Forge version, but it might work.

**Comment by D3nnis3n** [comment] 2017-10-16 11:09
Not quite, no.

http://minecraft.godsofwar.de/video2.mp4

**Comment by TominoCZ** [comment] 2017-10-16 12:13
O_O why are the particles flying in random direction?

**Comment by D3nnis3n** [comment] 2017-10-16 12:20
This is not a bug, it’s a Feature of CoroUtils Weather Mod. They fly in the direction and the Speed of the wind.

Gesendet von Mail für Windows 10

Von: TominoCZ
Gesendet: Montag, 16. Oktober 2017 14:13
An: TominoCZ/FancyBlockParticles
Cc: D3nnis3n; Comment
Betreff: Re: [TominoCZ/FancyBlockParticles] Strange Issue with FBP+Optifine(Beta)+BetterFPS (#22)

O_O why are the particles flying in random direction?

**Comment by TominoCZ** [comment] 2017-11-26 17:48
fixed in version 2.3.2.

**Closed by TominoCZ** 2017-11-26 17:48 UTC
